baseURL = 'https://playverv.github.io/AAC.Manual/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = ["github.com/McShelby/hugo-theme-relearn"]


[module]
[[module.imports]]
  path = 'github.com/McShelby/hugo-theme-relearn'
